//
//  CountryCatalog.swift
//  ADAXIntegra
//
//  Created by Eduardo Hernández Alonso on 22/09/26.
//

import Foundation

// Static catalog of supported countries: all Latin American countries plus
// Canada and the United States, with their states. Written in Spanish and
// alphabetically sorted. The country list is sorted by "name".
extension Country {
  static let all: [Country] = [
    argentina,
    bolivia,
    brasil,
    canada,
    chile,
    colombia,
    costaRica,
    cuba,
    ecuador,
    elSalvador,
    estadosUnidos,
    guatemala,
    haiti,
    honduras,
    mexico,
    nicaragua,
    panama,
    paraguay,
    peru,
    puertoRico,
    republicaDominicana,
    uruguay,
    venezuela,
  ]

  // Latin America
  static let argentina = Country(
    isoCode: "AR",
    name: "Argentina",
    dialCode: "+54",
    states: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Ciudad Autónoma de Buenos Aires",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ]
  )

  static let bolivia = Country(
    isoCode: "BO",
    name: "Bolivia",
    dialCode: "+591",
    states: [
      "Beni",
      "Chuquisaca",
      "Cochabamba",
      "La Paz",
      "Oruro",
      "Pando",
      "Potosí",
      "Santa Cruz",
      "Tarija",
    ]
  )

  static let brasil = Country(
    isoCode: "BR",
    name: "Brasil",
    dialCode: "+55",
    states: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahía",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande del Norte",
      "Rio Grande del Sur",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ]
  )

  static let chile = Country(
    isoCode: "CL",
    name: "Chile",
    dialCode: "+56",
    states: [
      "Antofagasta",
      "Arica y Parinacota",
      "Atacama",
      "Aysén",
      "Biobío",
      "Coquimbo",
      "La Araucanía",
      "Los Lagos",
      "Los Ríos",
      "Magallanes",
      "Maule",
      "Metropolitana de Santiago",
      "Ñuble",
      "O'Higgins",
      "Tarapacá",
      "Valparaíso",
    ]
  )

  static let colombia = Country(
    isoCode: "CO",
    name: "Colombia",
    dialCode: "+57",
    states: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bogotá D.C.",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés y Providencia",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupés",
      "Vichada",
    ]
  )

  static let costaRica = Country(
    isoCode: "CR",
    name: "Costa Rica",
    dialCode: "+506",
    states: [
      "Alajuela",
      "Cartago",
      "Guanacaste",
      "Heredia",
      "Limón",
      "Puntarenas",
      "San José",
    ]
  )

  static let cuba = Country(
    isoCode: "CU",
    name: "Cuba",
    dialCode: "+53",
    states: [
      "Artemisa",
      "Camagüey",
      "Ciego de Ávila",
      "Cienfuegos",
      "Granma",
      "Guantánamo",
      "Holguín",
      "Isla de la Juventud",
      "La Habana",
      "Las Tunas",
      "Matanzas",
      "Mayabeque",
      "Pinar del Río",
      "Sancti Spíritus",
      "Santiago de Cuba",
      "Villa Clara",
    ]
  )

  static let ecuador = Country(
    isoCode: "EC",
    name: "Ecuador",
    dialCode: "+593",
    states: [
      "Azuay",
      "Bolívar",
      "Cañar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galápagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Ríos",
      "Manabí",
      "Morona Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsáchilas",
      "Sucumbíos",
      "Tungurahua",
      "Zamora Chinchipe",
    ]
  )

  static let elSalvador = Country(
    isoCode: "SV",
    name: "El Salvador",
    dialCode: "+503",
    states: [
      "Ahuachapán",
      "Cabañas",
      "Chalatenango",
      "Cuscatlán",
      "La Libertad",
      "La Paz",
      "La Unión",
      "Morazán",
      "San Miguel",
      "San Salvador",
      "San Vicente",
      "Santa Ana",
      "Sonsonate",
      "Usulután",
    ]
  )

  static let guatemala = Country(
    isoCode: "GT",
    name: "Guatemala",
    dialCode: "+502",
    states: [
      "Alta Verapaz",
      "Baja Verapaz",
      "Chimaltenango",
      "Chiquimula",
      "El Progreso",
      "Escuintla",
      "Guatemala",
      "Huehuetenango",
      "Izabal",
      "Jalapa",
      "Jutiapa",
      "Petén",
      "Quetzaltenango",
      "Quiché",
      "Retalhuleu",
      "Sacatepéquez",
      "San Marcos",
      "Santa Rosa",
      "Sololá",
      "Suchitepéquez",
      "Totonicapán",
      "Zacapa",
    ]
  )

  static let haiti = Country(
    isoCode: "HT",
    name: "Haití",
    dialCode: "+509",
    states: [
      "Artibonito",
      "Centro",
      "Grand'Anse",
      "Nippes",
      "Nordeste",
      "Noroeste",
      "Norte",
      "Oeste",
      "Sudeste",
      "Sur",
    ]
  )

  static let honduras = Country(
    isoCode: "HN",
    name: "Honduras",
    dialCode: "+504",
    states: [
      "Atlántida",
      "Choluteca",
      "Colón",
      "Comayagua",
      "Copán",
      "Cortés",
      "El Paraíso",
      "Francisco Morazán",
      "Gracias a Dios",
      "Intibucá",
      "Islas de la Bahía",
      "La Paz",
      "Lempira",
      "Ocotepeque",
      "Olancho",
      "Santa Bárbara",
      "Valle",
      "Yoro",
    ]
  )

  static let mexico = Country(
    isoCode: "MX",
    name: "México",
    dialCode: "+52",
    states: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Ciudad de México",
      "Coahuila",
      "Colima",
      "Durango",
      "Estado de México",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ]
  )

  static let nicaragua = Country(
    isoCode: "NI",
    name: "Nicaragua",
    dialCode: "+505",
    states: [
      "Boaco",
      "Carazo",
      "Chinandega",
      "Chontales",
      "Costa Caribe Norte",
      "Costa Caribe Sur",
      "Estelí",
      "Granada",
      "Jinotega",
      "León",
      "Madriz",
      "Managua",
      "Masaya",
      "Matagalpa",
      "Nueva Segovia",
      "Río San Juan",
      "Rivas",
    ]
  )

  static let panama = Country(
    isoCode: "PA",
    name: "Panamá",
    dialCode: "+507",
    states: [
      "Bocas del Toro",
      "Chiriquí",
      "Coclé",
      "Colón",
      "Darién",
      "Emberá-Wounaan",
      "Guna Yala",
      "Herrera",
      "Los Santos",
      "Ngäbe-Buglé",
      "Panamá",
      "Panamá Oeste",
      "Veraguas",
    ]
  )

  static let paraguay = Country(
    isoCode: "PY",
    name: "Paraguay",
    dialCode: "+595",
    states: [
      "Alto Paraguay",
      "Alto Paraná",
      "Amambay",
      "Asunción",
      "Boquerón",
      "Caaguazú",
      "Caazapá",
      "Canindeyú",
      "Central",
      "Concepción",
      "Cordillera",
      "Guairá",
      "Itapúa",
      "Misiones",
      "Ñeembucú",
      "Paraguarí",
      "Presidente Hayes",
      "San Pedro",
    ]
  )

  static let peru = Country(
    isoCode: "PE",
    name: "Perú",
    dialCode: "+51",
    states: [
      "Amazonas",
      "Áncash",
      "Apurímac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huánuco",
      "Ica",
      "Junín",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martín",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ]
  )

  static let puertoRico = Country(
    isoCode: "PR",
    name: "Puerto Rico",
    dialCode: "+1",
    states: []
  )

  static let republicaDominicana = Country(
    isoCode: "DO",
    name: "República Dominicana",
    dialCode: "+1",
    states: [
      "Azua",
      "Baoruco",
      "Barahona",
      "Dajabón",
      "Distrito Nacional",
      "Duarte",
      "El Seibo",
      "Elías Piña",
      "Espaillat",
      "Hato Mayor",
      "Hermanas Mirabal",
      "Independencia",
      "La Altagracia",
      "La Romana",
      "La Vega",
      "María Trinidad Sánchez",
      "Monseñor Nouel",
      "Monte Cristi",
      "Monte Plata",
      "Pedernales",
      "Peravia",
      "Puerto Plata",
      "Samaná",
      "San Cristóbal",
      "San José de Ocoa",
      "San Juan",
      "San Pedro de Macorís",
      "Sánchez Ramírez",
      "Santiago",
      "Santiago Rodríguez",
      "Santo Domingo",
      "Valverde",
    ]
  )

  static let uruguay = Country(
    isoCode: "UY",
    name: "Uruguay",
    dialCode: "+598",
    states: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavalleja",
      "Maldonado",
      "Montevideo",
      "Paysandú",
      "Río Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San José",
      "Soriano",
      "Tacuarembó",
      "Treinta y Tres",
    ]
  )

  static let venezuela = Country(
    isoCode: "VE",
    name: "Venezuela",
    dialCode: "+58",
    states: [
      "Amazonas",
      "Anzoátegui",
      "Apure",
      "Aragua",
      "Barinas",
      "Bolívar",
      "Carabobo",
      "Cojedes",
      "Delta Amacuro",
      "Dependencias Federales",
      "Distrito Capital",
      "Falcón",
      "Guárico",
      "La Guaira",
      "Lara",
      "Mérida",
      "Miranda",
      "Monagas",
      "Nueva Esparta",
      "Portuguesa",
      "Sucre",
      "Táchira",
      "Trujillo",
      "Yaracuy",
      "Zulia",
    ]
  )

  // North America
  static let canada = Country(
    isoCode: "CA",
    name: "Canadá",
    dialCode: "+1",
    states: [
      "Alberta",
      "Columbia Británica",
      "Isla del Príncipe Eduardo",
      "Manitoba",
      "Nueva Escocia",
      "Nuevo Brunswick",
      "Nunavut",
      "Ontario",
      "Quebec",
      "Saskatchewan",
      "Terranova y Labrador",
      "Territorios del Noroeste",
      "Yukón",
    ]
  )

  static let estadosUnidos = Country(
    isoCode: "US",
    name: "Estados Unidos de América",
    dialCode: "+1",
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Carolina del Norte",
      "Carolina del Sur",
      "Colorado",
      "Connecticut",
      "Dakota del Norte",
      "Dakota del Sur",
      "Delaware",
      "Distrito de Columbia",
      "Florida",
      "Georgia",
      "Hawái",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Luisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Misisipi",
      "Misuri",
      "Montana",
      "Nebraska",
      "Nevada",
      "Nueva Jersey",
      "Nueva York",
      "Nuevo Hampshire",
      "Nuevo México",
      "Ohio",
      "Oklahoma",
      "Oregón",
      "Pensilvania",
      "Rhode Island",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Virginia Occidental",
      "Washington",
      "Wisconsin",
      "Wyoming",
    ]
  )
}
